# Generated by Django 5.1.6 on 2025-02-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(help_text='City or Area', max_length=255)),
                ('incident_type', models.CharField(choices=[('harassment', 'Harassment'), ('domestic_violence', 'Domestic Violence'), ('workplace_discrimination', 'Workplace Discrimination'), ('other', 'Other')], default='other', max_length=50)),
                ('incident_date', models.DateField(help_text='Date of Incident')),
                ('complaint', models.TextField(help_text='Describe the incident in detail')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('feedback', models.TextField(help_text='Provide your feedback')),
                ('rating', models.CharField(choices=[('average', 'Average'), ('good', 'Good'), ('poor', 'Poor')], default='good', max_length=10)),
                ('suggestion', models.TextField(blank=True, help_text='Any suggestions?', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('confirm_password', models.CharField(max_length=128)),
                ('emergency_contact1', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_contact2', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
